# permissions for end users to view nsscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nsscaler-viewer-role
rules:
- apiGroups:
  - operators.wubw.fun
  resources:
  - nsscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.wubw.fun
  resources:
  - nsscalers/status
  verbs:
  - get
