
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operators.wubw.fun
  resources:
  - nsscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.wubw.fun
  resources:
  - nsscalers/finalizers
  verbs:
  - update
- apiGroups:
  - operators.wubw.fun
  resources:
  - nsscalers/status
  verbs:
  - get
  - patch
  - update
